# Node.js with Grunt on Linux Web App
# Build a Node.js project using the Grunt task runner and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy Node.js with Webpack on Linux Web App

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    # login using azure credentials
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.linux554_9313 }}

    - uses: actions/setup-node@v1
      with:
        node-version: 10.x

    # install dependencies, build, and test
    - name: npm install, build
      working-directory: .
      run: |
        npm install -g webpack webpack-cli --save-dev
        npm install
        npx webpack --config webpack.config.js

    - uses: azure/appservice-settings@v1
      with:
        app-name: linux554
        general-settings-json: '{"linuxFxVersion": "NODE|10-lts"}' #'General configuration settings as Key Value pairs'

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: linux554
        package: .

    # Azure logout
    - name: logout
      run: |
        az logout